services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: software-slayer-db
      MYSQL_USER: software-slayer
      MYSQL_PASSWORD: software-slayer-password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./db/sql/:/docker-entrypoint-initdb.d
    
  software-slayer-server:
    image: software-slayer-server
    container_name: software-slayer-server
    ports:
      - "8080:8080"
    
volumes:
  mysql: