name: Client CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install --prefix ./client
    
    - name: Lint code
      run: npm run lint:ci --prefix ./client && npm run format:check --prefix ./client

    - name: Run tests
      run: npm test --prefix ./client